export const navItems = [
  { label: 'Tổng quan', icon: 'LayoutDashboard' },
  { label: 'Lịch dạy', icon: 'CalendarDays' },
  { label: 'Giáo án', icon: 'BookOpen' },
  { label: 'Thư viện hoạt động', icon: 'Library' },
  { label: 'Lớp học', icon: 'Users' },
  { label: 'Học sinh', icon: 'GraduationCap' },
  { label: 'Phiếu học tập', icon: 'Files' },
  { label: 'Đánh giá', icon: 'ClipboardCheck' },
  { label: 'Chủ nhiệm', icon: 'School' },
  { label: 'Điểm danh', icon: 'CheckCircle2' },
  { label: 'Báo cáo & Thống kê', icon: 'FileText' },
  { label: 'Tài nguyên', icon: 'Files' },
  { label: 'Cài đặt', icon: 'Settings' },
  { label: 'Trợ lý AI', icon: 'Sparkles' },
  { label: 'Mẫu của tôi', icon: 'Bookmark' },
  { label: 'Nhận xét nhanh', icon: 'MessageSquarePlus' },
  { label: 'Sơ đồ chỗ ngồi', icon: 'Grid2X2' },
]
